name: topic_gpt_gpu
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - sqlalchemy
  - pyodbc
  - sentence-transformers
  - transformers
  - accelerate
  - anytree
  - openai
  - nb_conda_kernels
  - numpy
  - pandas
  - regex
  - jupyter
  - tqdm
  - requests
  - pytz
  - tenacity
  - tiktoken
  - pytorch::pytorch>=2.5.1
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch-cuda=11.8
  - cuda-toolkit
  - protobuf
  - sentencepiece
  - optimum
  - pip 
  - pip:
    - auto_gptq