name: topic_gpt
channels:
  - conda-forge
dependencies:
  - python=3.11
  - sqlalchemy
  - pyodbc
  - sentence-transformers
  - anytree
  - openai
  - nb_conda_kernels
  - numpy
  - pandas
  - regex
  - jupyter
  - tqdm
  - requests
  - pytz
  - tenacity
  - tiktoken