name: topic_gpt_gpu_updated
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - sqlalchemy
  - pyodbc
  - sentence-transformers
  - transformers
  - accelerate
  - anytree
  - openai
  - nb_conda_kernels
  - numpy
  - pandas
  - regex
  - jupyter
  - tqdm
  - requests
  - pytz
  - tenacity
  - tiktoken
  - pytorch::pytorch>=2.5.1
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch-cuda=12.1
  - nvidia::cuda-toolkit==12.1
  - protobuf
  - sentencepiece
  - optimum
  - pip 
  - pip:
    - auto_gptq
    - topicgpt_python
    - vllm
    - python-resources
    - https://huggingface.co/madbuda/triton-windows-builds/resolve/main/triton-3.0.0-cp311-cp311-win_amd64.whl