name: topicgpt
channels:
  - conda-forge
dependencies:
  - python=3.11
  - sentence-transformers
  - nb_conda_kernels
  - numpy
  - pandas
  - jupyter
  - tqdm
  - requests
  - pip
  - pip:
    - anytree==2.12.1
    - openai==1.3.3
    - pytz==2023.3
    - regex==2023.8.8
    - tenacity==8.2.3
    - tiktoken==0.5.1